keys:
  - &admin age1epcht3qe6977l3klzdcpqjzr4lrpz7v5tp4cxzfzls8ppm0ptg7syntqqh
  - &boron age1gmtdsenacykqk36eefgnhaul72ud8a8p5e9d0qn9g9xxhyv30ckqh85lex
  - &carbon age1tampdp59kp5a4q2mz3wmwpvv4xv0p0ez6mndnru8wvc9tv00k4gqsln8v3
  - &oxygen age1zlmelu5wtfeqvryl8ff7zkwvdwez435cyppxmm58q7k9pxylj3asttpls5

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
        - *admin
        - *boron
        - *carbon
        - *oxygen
  - path_regex: secrets/carbon\.yaml$
    key_groups:
      - age:
        - *admin
        - *carbon
  - path_regex: secrets/boron\.yaml$
    key_groups:
      - age:
        - *admin
        - *boron
  - path_regex: secrets/lithium\.yaml$
    key_groups:
      - age:
        - *admin
  - path_regex: secrets/oxygen\.yaml$
    key_groups:
      - age:
        - *admin
        - *oxygen
