name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flake-check:
    runs-on: x86_64-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nix flake check
        run: nix flake check
